name: Conda Deploy

on:
  push:
    branches:
      - conda

env:
  DOCKER_ORG: cormorack
  IMAGE_NAME: uvicorn-gunicorn

jobs:
  build-deploy:
    strategy:
      matrix:
        image:
          - conda_version: "4.9.2" 
            python_version: "3.7"
          - conda_version: "4.9.2" 
            python_version: "3.8"
          - conda_version: "4.9.2" 
            python_version: "3.9"
      fail-fast: true
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2
      - name: Set Docker Image Spec
        run: |
          DOCKER_TAG=python${{ matrix.image.python_version }}-conda${{ matrix.image.conda_version }}
          IMAGE_SPEC="${{ env.DOCKER_ORG }}/${{ env.IMAGE_NAME }}:${DOCKER_TAG}"
          echo "IMAGE_SPEC=${IMAGE_SPEC}" >> $GITHUB_ENV
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Login to DockerHub
        uses: docker/login-action@v1 
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_TOKEN }}
      - name: Build Docker Image
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          context: ./docker-images
          file: ./docker-images/conda.dockerfile
          push: true
          build-args: |
            CONDA_VERSION=${{ matrix.image.conda_version }}
            PYTHON_VERSION=${{ matrix.image.python_version }}
          tags: |
            ${{ env.IMAGE_SPEC }}