name: Test

on:
  push:
  pull_request:
    types: [opened, synchronize]

env:
  DOCKER_ORG: cormorack
  IMAGE_NAME: uvicorn-gunicorn

jobs:
  build:
    strategy:
      matrix:
        image:
          - name: latest
            python_version: "3.8"
          - name: python3.8
            python_version: "3.8"
          - name: python3.7
            python_version: "3.7"
          - name: python3.6
            python_version: "3.6"
          - name: python3.8-slim
            python_version: "3.8"
          - name: python3.8-alpine3.10
            python_version: "3.8"
          - name: python3.7-alpine3.8
            python_version: "3.7"
          - name: python3.6-alpine3.8
            python_version: "3.6"
      fail-fast: true
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python
        uses: actions/setup-python@v1
        with:
          python-version: "3.7"
      - name: Install Dependencies
        run: python3.7 -m pip install docker pytest
      - name: Test Image
        run: bash scripts/test.sh
        env:
          NAME: ${{ matrix.image.name }}
          PYTHON_VERSION: ${{ matrix.image.python_version }}
  conda-build:
    strategy:
      matrix:
        image:
          - conda_version: "4.9.2" 
            python_version: "3.7"
          - conda_version: "4.9.2" 
            python_version: "3.8"
          - conda_version: "4.9.2" 
            python_version: "3.9"
      fail-fast: true
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python
        uses: actions/setup-python@v1
        with:
          python-version: "3.7"
      - name: Install Dependencies
        run: python3.7 -m pip install docker pytest
      - name: Set Docker Image Spec
        run: |
          DOCKER_TAG=python${{ matrix.image.python_version }}-conda${{ matrix.image.conda_version }}
          IMAGE_SPEC="${{ env.DOCKER_ORG }}/${{ env.IMAGE_NAME }}:${DOCKER_TAG}"
          echo "IMAGE_SPEC=${IMAGE_SPEC}" >> $GITHUB_ENV
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Build Docker Image
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          context: ./docker-images
          file: ./docker-images/conda.dockerfile
          push: false
          build-args: |
            CONDA_VERSION=${{ matrix.image.conda_version }}
            PYTHON_VERSION=${{ matrix.image.python_version }}
          tags: |
            ${{ env.IMAGE_SPEC }}
      - name: Test Image
        run: python3.7 -m pytest tests
        env:
          IMAGE_SPEC: ${{ env.IMAGE_SPEC }}
          PYTHON_VERSION: ${{ matrix.image.python_version }}
